### ISSUE TITLE
[Bug]: KryptonThemeComboBox: invalid designer code generation [alpha-1309]

### ISSUE THREAD

**Issue by tobitege** [Krypton-Suite/Standard-Toolkit#1328]
**KryptonThemeComboBox generates wrong code in designer file**

Saving a form with such component writes a line like below to the designer.cs file:  

`this.kryptonThemeComboBox1.ThemeSelectedIndex = 24;`  

Compiler errors then as ThemeSelectedIndex is not writable.  
Removing that line manually fixes the error.

@Wagnerp I'm currently working on the alpha-derived branch named 1309-xxx, but I'd guess it is happening in alpha as well, if not also in the Canary branch.

**Expected behavior**
The above property should either not be written to the designer file or be made accessible.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2
 - Framework/.NET Version: 4.8.x
 - Toolkit Version: current alpha

**Comment by Wagnerp** [comment]
Hi @tobitege 

It's set at the wrong index, the default should be `Microsoft 365 - Blue` at 3x.

**Comment by Wagnerp** [comment]
This  _should_ stop it

```[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]```

**Comment by tobitege** [comment]
When manually in form design mode switching the DefaultPalette to a different theme like e.g. Office2010Black it correctly writes this line to the designer:  
this.kryptonThemeComboBox1.DefaultPalette = Krypton.Toolkit.PaletteMode.Office2010Black;  
(that's where the mentioned ThemeSelectedIndex line came from).

However, there is still the issue, that changing the property in the Properties at design time, it still displays the wrong text inside the combo:  
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/d07dba7c-7662-44bd-88c8-35a4a8054d5b)

Form designer:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/70537838-ea8a-4bfe-95c9-8ce16f69a060)

**Comment by Wagnerp** [comment]
It's not pairing up for some reason? Its always off by 1 or 2

**Comment by tobitege** [comment]
> It's not pairing up for some reason? Its always off by 1 or 2

Yes, it is off by 1 in this example. I thought that was already fixed last week? 🤔

**Comment by tobitege** [comment]
Your commit [d13426d](https://github.com/Krypton-Suite/Standard-Toolkit/commit/d13426d9d7a56166fe39fed4709395d027ff8f84) should not hide the **DefaultPalette** property.
Now it is not showing in the form designer properties.

**Comment by tobitege** [comment]
Your commit [d13426d](https://github.com/Krypton-Suite/Standard-Toolkit/commit/d13426d9d7a56166fe39fed4709395d027ff8f84) should not hide the **DefaultPalette** property.

Edit: it is visible in the form designer, but not written to the designer file anymore.

**Comment by Wagnerp** [comment]
> Your commit [d13426d](https://github.com/Krypton-Suite/Standard-Toolkit/commit/d13426d9d7a56166fe39fed4709395d027ff8f84) should not hide the **DefaultPalette** property. Now it is not showing in the form designer properties.

Undo some changes

**Comment by Smurf-IV** [comment]
> > Your commit [d13426d](https://github.com/Krypton-Suite/Standard-Toolkit/commit/d13426d9d7a56166fe39fed4709395d027ff8f84) should not hide the **DefaultPalette** property. Now it is not showing in the form designer properties.
> 
> Undo some changes

@Wagnerp What is the state of this ?
i.e. 
- Some Changes 
- - or all changes 
- or still broken as per original 
-  something else ?

**Comment by Wagnerp** [comment]
> > > Your commit [d13426d](https://github.com/Krypton-Suite/Standard-Toolkit/commit/d13426d9d7a56166fe39fed4709395d027ff8f84) should not hide the **DefaultPalette** property. Now it is not showing in the form designer properties.
> > 
> > 
> > Undo some changes
> 
> @Wagnerp What is the state of this ? i.e.
> 
> * Some Changes
> * * or all changes
> * or still broken as per original
> * something else ?

@Smurf-IV The ribbon version is still out by + 2 and they both still don't sync properly with `KryptonManager` changes. I did have a go at trying to fix the ribbon version, _but_ discovered that ribbon controls don't have access to `Handle`. See @tobitege  PR #1331, specifically `KryptonThemeComboBox.cs`

**Comment by tobitege** [comment]
Any news on this, it's been a while?

**Comment by giduac** [comment]
Hi @Wagnerp,

Pl;ease assign to me.
Thank you!

**Comment by giduac** [comment]
Hi @Wagnerp,

I have a question:
`PaletteMode' `enum` and the `PaleteModeStrings.SupportedThemes` Dictionary 
Do these two lists have to be ordered in the same way ?

**Comment by giduac** [comment]
Hi @Wagnerp,
Could you please have a look at the above question asap?

This is a part of https://github.com/Krypton-Suite/Standard-Toolkit/issues/1328

**Comment by giduac** [comment]
@Wagnerp @Smurf-IV,

Will the KryptonThemeListBox be removed since this not present in the Toolbox anymore?

```cs
[ToolboxItem(false)]
    [Designer(typeof(KryptonThemeBrowserDesigner))]
    public class KryptonThemeListBox : KryptonListBox
```

**Comment by giduac** [comment]
Hi @tobitege ,

I have a bit of a hard time extracting the correct description from the above.
Can you please give a clear and complete description of the problem(s).

**Comment by giduac** [comment]
FYI.
In this fix there will several alterations. 
One of the problems with selecting themes are inconsistencies in the order of the `PaletteMode` `Enum` and the `PaletteModeStrings.SupprotedThemes` Dictionary.
This order will be corrected and the _SupportedThemes order will be leading._

I would like to ask to make no changes to the two until this issue is complete.
This is the order of the two currently with the discrepancies between the two.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/414e1443-6417-4f62-accf-01b485d447ec)

The PaletteMode enum is used a lot to retrieve the index and that is where things are out of sync atm.
Since the PaletteMode starts with the Global entry the theme index is currently 1 off (if the order was correct).
Therefore PaletteMode will be started with a value of Global = -1. And next the entry is the first theme which will receive the value 0. Which is a valid index.

Also the three theme selector controls will be hooked up to the KManager change event so all stays in sync when a theme is changed from outside the theme selector controls.

I suggest to first make this for alpha and then we can see how much of that will fit in V85 or is desirable.

**Comment by giduac** [comment]
Hi @tobitege,

I just posted a PR that should resolve your problems with the KThemeCBB.
Probably will be merged into alpha tomorrow.

Keep us posted please about your findings.

TY.

**Comment by tobitege** [comment]
Thanks so much!
Apologies for the late reply, I'll give it a try with the next alpha, but could be a day or two.

**Comment by giduac** [comment]
@Wagnerp

I've asked @tobitege a couple of times to test the fix, but no response.
Please close the ticket. If needed it can be reopened.

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> I've asked @tobitege a couple of times to test the fix, but no response. Please close the ticket. If needed it can be reopened.

@giduac Can I apply the 'fixed' label?

**Comment by giduac** [comment]
@Wagnerp 
Very  much so :)
