### ISSUE TITLE
[Bug]: `KryptonCustomPaletteBase`, Unable to Set / Change the colour table (help to migrate to v90.)

### ISSUE THREAD

**Issue by lesandrog** [Krypton-Suite/Standard-Toolkit#1870]
In version 85, I was using a KryptonCustomPaletteBase with BasePaletteMode = Office2010Silver, with some modifications.

But I'm not able to migrate to v90.

I must be doing something wrong.
![image](https://github.com/user-attachments/assets/e684d446-3605-4f7e-bf38-f37ff54aeb1e)

**Comment by lesandrog** [comment]
Can anyone help me?

**Comment by PWagner1** [comment]
Hi @lesandrog 

The `KryptonCustomPaletteBase` has gone through a significant overhaul in V90. You may need to set the `BasePaletteType` located under `BasePalette`, see https://github.com/Krypton-Suite/Standard-Toolkit?tab=readme-ov-file#v9000-2024-11-12---build-2411---november-2024 for breaking changes.

**Comment by lesandrog** [comment]
Hi @PWagner1 

When I add the KryptonManager and set GlobalCustomPalette = KryptonCustomPaletteBase1.
I set in KryptonCustomPaletteBase1.BasePaletteType = Office2010

The colors are still Microsoft 365 - Blue.

In BasePaletteType, should there be more options (Office 2010 - Silver, Office 2010 - White)?
![image](https://github.com/user-attachments/assets/77f98cf0-8647-40ae-9164-1dd7e05c96b1)

**Comment by PWagner1** [comment]
@Smurf-IV ??

**Comment by Smurf-IV** [comment]
> In BasePaletteType, should there be more options (Office 2010 - Silver, Office 2010 - White)?

No it `BaseRenderMode`, and this has nothing to do with the colours, as they are defined in the actual XML.

>The colors are still Microsoft 365 - Blue.


The default colours come from the `BasePalette`'s `ColourTable`:
![image](https://github.com/user-attachments/assets/9c0ede07-5583-4d6b-82a1-72b09869c73e)
(Defined in the XML? @PWagner1 )
And then are overridden by the extra colours as defined in the actual custom palettes XML or defined in the designer

**Comment by lesandrog** [comment]
hi, @PWagner1 and @Smurf-IV 

So, from what I understand, to use KryptonCustomPaletteBase1 with the Office 2010 - Silver colors and some customizations (or if you want to customize another theme), I will have to import a complete XML with all the parameters.

In my humble opinion, it is not very practical.
Or I don't know how to use it.

**Comment by Smurf-IV** [comment]
> In my humble opinion, it is not very practical.

Agreed!
The colour Table stuff does not appear to change anymore like it used to in the V8# code base:
![image](https://github.com/user-attachments/assets/8ef03ce4-aaf8-490d-b3b6-d28b32fb799f)

**Comment by Smurf-IV** [comment]
@lesandrog Can you open your V80 xml and just change the version number to 20.
Does this then work as expected ?

**Comment by lesandrog** [comment]
@Smurf-IV , I had already done this test of changing v19 to v20. The result is partial, the colors that are in the custom xml are loaded correctly, but items that are not present in the xml continue with the default Microsoft365blue colors.


![image](https://github.com/user-attachments/assets/377d6379-2e63-4ba5-95ed-ebfcb6e936e0) In Palette Designer v85, creating a new one with BasePaletteMode, the theme colors were loaded. In v90 using BaseRenderMode the colors remain the same as 365blue.
.

![image](https://github.com/user-attachments/assets/77cf94b2-45d2-4033-a377-5a83e763c723) When importing a custom XML, only the custom items are changed, the other items continue with the default theme colors, microsoft365blue.
.

![image](https://github.com/user-attachments/assets/0737580c-9156-4afb-9b2f-2bf8b30f19f5) The best result was to export an xml after using the "Populate from base" function in a v85 project and then use it in v90.
This way all the colors of the BasePalettemode are exported.
I am using the Office2010silver theme, but it is the same for other themes.
.

![image](https://github.com/user-attachments/assets/68266a8f-46b4-47fc-8f52-b4fdecbb1cd0) One disadvantage of using the "Populate from Base" function in a v85 project is that in some themes, some items are not populated, such as ToolMenuStatus. Manual editing is required.

**Comment by giduac** [comment]
@lesandrog 

Took a while, but we are all busy atm.

This should solve the palette assignment in V100 (for now).
It will be part of V100 build .81 or later.

Keep us posted thanks.

**Comment by lesandrog** [comment]
Hello, @giduac 
I understand perfectly, the priority is for functional issues and not aesthetics.

I found a solution for V90, which is to add in the loading event
"KryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2010Silver)".

I will still test in v100  .81, when it is available on nuget.

**Comment by giduac** [comment]
Hi @lesandrog 

.90 nightly has arrived
Yes you can assign a built-in theme to `BasePalette` that way.

**Comment by lesandrog** [comment]
@giduac 
I tested .90 nightly, but I didn't see any difference compared to the previous ones. It is still not possible to assign a color palette to KryptonCustomPaletteBase, like the old BasePaletteMode property.

The best result is still to put the code manually
"KryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2010Silver)".

**Comment by giduac** [comment]
> [@giduac](https://github.com/giduac) I tested .90 nightly, but I didn't see any difference compared to the previous ones. It is still not possible to assign a color palette to KryptonCustomPaletteBase, like the old BasePaletteMode property.
> 
> The best result is still to put the code manually "KryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2010Silver)".

`TheBasePaletteMode` property has been taken out.
Just use the `BasePalette` property as you stated above to assign the base theme you want to use.

**Comment by giduac** [comment]
> [@Smurf-IV](https://github.com/Smurf-IV) , I had already done this test of changing v19 to v20. The result is partial, the colors that are in the custom xml are loaded correctly, but items that are not present in the xml continue with the default Microsoft365blue colors.
> 
> ![image](https://github.com/user-attachments/assets/377d6379-2e63-4ba5-95ed-ebfcb6e936e0) In Palette Designer v85, creating a new one with BasePaletteMode, the theme colors were loaded. In v90 using BaseRenderMode the colors remain the same as 365blue. .
> 
> ![image](https://github.com/user-attachments/assets/77cf94b2-45d2-4033-a377-5a83e763c723) When importing a custom XML, only the custom items are changed, the other items continue with the default theme colors, microsoft365blue. .
> 
> ![image](https://github.com/user-attachments/assets/0737580c-9156-4afb-9b2f-2bf8b30f19f5) The best result was to export an xml after using the "Populate from base" function in a v85 project and then use it in v90. This way all the colors of the BasePalettemode are exported. I am using the Office2010silver theme, but it is the same for other themes. .
> 
> ![image](https://github.com/user-attachments/assets/68266a8f-46b4-47fc-8f52-b4fdecbb1cd0) One disadvantage of using the "Populate from Base" function in a v85 project is that in some themes, some items are not populated, such as ToolMenuStatus. Manual editing is required.

Hi @lesandrog,

A question.

We are working on a big change to make the built-in themes editable through custom palettes in the Palette Designer. This involves quite a bit of work...

One of the things on the list is doing a full checkup/test on the `KryptonCustomPaletteBase`. You already did a bit of that work here.
So the questions is, would you like to contribute some time in doing a full checkup on the `KryptonCustomPaletteBase` class and it's use in the palette designer?

**Comment by lesandrog** [comment]
@giduac 
I'm an amateur programmer, I do this just for fun.
If you tell me exactly what needs to be done, yes I can help.

If it's written wrong, it's the translator's fault, I don't speak English, heheheh.

**Comment by giduac** [comment]
Hi @lesandrog,

I've had a couple of days off.

Great!
If you don't try ....

And of course we will always help you out with stuff.

So I'll get back to you later this week to get you started.

**Comment by giduac** [comment]
Hi @lesandrog,

Before we move on later this week, please get yourself acquainted with [Contributing to the Standard Toolkit
](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Contributing.html)

**Comment by giduac** [comment]
Hi @lesandrog,

Is this one still on after the latest theming changes?

**Comment by lesandrog** [comment]
@giduac 
Even in the current V100, we have the following situations:

In `kryptonCustomPaletteBase`, the default theme is `Microsoft 365 - Blue`, and it cannot be changed.

If you use the Palette Designer, and use the "New from Default Theme" option, you save an XML file with the Office 2007 - Silver theme colors.
And then import it into `kryptonCustomPaletteBase1`, the colors are applied without error, but some styles are not changed.
<img width="889" height="346" alt="Image" src="https://github.com/user-attachments/assets/b818122a-be6c-41a3-8268-6e49b762ae56" />

The best result is still to use the code to change the theme base:
`kryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2007Silver)`
<img width="889" height="363" alt="Image" src="https://github.com/user-attachments/assets/99f01964-1d12-4567-b6ec-37160854684a" />

Shouldn't the `BasePalette` property of `kryptonCustomPaletteBase` in the designer load the theme list?
<img width="476" height="212" alt="Image" src="https://github.com/user-attachments/assets/1283719d-78d0-4a91-ad10-74e9ade04f01" />

Would updating this property in the designer solve the problem?

**Comment by giduac** [comment]
Hi @lesandrog,

I will try today or tomorrow and spend time on your remarks. Stay tuned...

**Comment by PWagner1** [comment]
> Hi [@lesandrog](https://github.com/lesandrog),
> 
> I will try today or tomorrow and spend time on your remarks. Stay tuned...

Hi @giduac 

I'd say focus on V100 & V85, as V95 will be EOL in a few weeks time.

**Comment by lesandrog** [comment]
> > Olá [@lesandrog](https://github.com/lesandrog) ,
> > Tentarei hoje ou amanhã e dedicarei um tempo aos seus comentários. Fique ligado...
> 
> Oi[@giduac](https://github.com/giduac)
> 
> Eu diria para focar no V100 e no V85, já que o V95 chegará ao fim de vida útil em algumas semanas.

So you can just focus on the v100.
The V85 doesn't have this problem.

**Comment by giduac** [comment]
Hi @lesandrog,

We (or at least I) don't know how this exactly is supposed to behave/function before addressing this. We probably will bump in to thing or two more...

Does V85 work correct or is it partially flawed ?

**Comment by lesandrog** [comment]
Works correctly in version 85.


I'll try to explain better.
Until v85, when adding a `kryptonCustomPaletteBase`, it was possible to set the `BasePaletteMode`.
If I set `Office 2007 Silver`, all colors and styles were applied.
And if necessary, only specific colors needed to be changed.

Starting with v95 (`BasePaletteMode` was removed).
The `kryptonCustomPaletteBase` defaults to the `Microsoft 365 Blue` theme. It's not possible to change it.
If I want the theme with Office 2007 Silver with some changes, I saw two ways to do it.
1. Edit all the properties of the kryptonCustomPaletteBase manually (impossible in my opinion) or import an XML file generated from Palette Designer (but this doesn't change everything).

2. Apply via code: `kryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2007Silver)`.
Behaving the same as `BasePaletteMode` from v85.
This way, kryptonCustomPaletteBase uses the base colors and styles of Office 2007 Silver.

**Comment by giduac** [comment]
> Works correctly in version 85.
> 
> I'll try to explain better. Until v85, when adding a `kryptonCustomPaletteBase`, it was possible to set the `BasePaletteMode`. If I set `Office 2007 Silver`, all colors and styles were applied. And if necessary, only specific colors needed to be changed.
> 
> Starting with v95 (`BasePaletteMode` was removed). The `kryptonCustomPaletteBase` defaults to the `Microsoft 365 Blue` theme. It's not possible to change it. If I want the theme with Office 2007 Silver with some changes, I saw two ways to do it.
> 
> 1. Edit all the properties of the kryptonCustomPaletteBase manually (impossible in my opinion) or import an XML file generated from Palette Designer (but this doesn't change everything).
> 2. Apply via code: `kryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2007Silver)`.
>    Behaving the same as `BasePaletteMode` from v85.
>    This way, kryptonCustomPaletteBase uses the base colors and styles of Office 2007 Silver.

That's how it should be.
As far as i have seen earlier 365 blue has been hard coded in V95.

If this will be changed, before that we need to take a look at the Palette Viewer / Palette designer to see if that will also be affected and how.

On the other hand if V85 is working correct when it comes to BasePaletteMode, we can have a look first how this behaviour/code can  be integrated into V100.

So we need to do some inventory, maybe some testing on a test branch, to come to a list of changes for V100 to restore this functionality.

**Comment by lesandrog** [comment]
I don't know why BasePaletteMode was removed.

I also don't know what use BasePalette has in the designer!
I tried adding the theme list there, but I couldn't do it..
It's still a bit advanced for me, lol.

**Comment by PWagner1** [comment]
> I don't know why BasePaletteMode was removed.
> 
> I also don't know what use BasePalette has in the designer! I tried adding the theme list there, but I couldn't do it.. It's still a bit advanced for me, lol.

I can't exactly remember, but this may help https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Standard%20Toolkit/Toolkit/KryptonCustomPaletteBase.html, https://github.com/Krypton-Suite/Standard-Toolkit/tree/V85-LTS?tab=readme-ov-file#breaking-changes & https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Breaking%20Changes.html

**Comment by giduac** [comment]
> I don't know why BasePaletteMode was removed.
> 
> I also don't know what use BasePalette has in the designer! I tried adding the theme list there, but I couldn't do it.. It's still a bit advanced for me, lol.

@lesandrog 

If you like, try figure out why in 85 switching worked as it did.
After that try to get an idea what is missing in 100 for that to work.

The more info we have the better. 
Then somewhere next week we can have a look together or whenever it suits.

**Comment by lesandrog** [comment]
Exactly what is mentioned in the documentation about BasePaletteMode. With its removal, it is no longer possible to do it.<img width="1351" height="284" alt="Image" src="https://github.com/user-attachments/assets/6fce0e36-859a-486f-844a-85c872dbc1d1" />

**Comment by lesandrog** [comment]
Now I understand the use of BasePalette. It's to transfer the base of kryptonCustomPaletteBase1 to kryptonCustomPaletteBase2, for example.
`this.kryptonCustomPaletteBase2.BasePalette = this.kryptonCustomPaletteBase1;`

But it's possible to assign an internal theme to BasePalette via code.
`kryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2007Silver)`
And, surprisingly, this works in v95 and later.

**Comment by giduac** [comment]
> Now I understand the use of BasePalette. It's to transfer the base of kryptonCustomPaletteBase1 to kryptonCustomPaletteBase2, for example. `this.kryptonCustomPaletteBase2.BasePalette = this.kryptonCustomPaletteBase1;`
> 
> But it's possible to assign an internal theme to BasePalette via code. `kryptonCustomPaletteBase1.BasePalette = KryptonManager.GetPaletteForMode(PaletteMode.Office2007Silver)` And, surprisingly, this works in v95 and later.

@lesandrog 
Then that procedure could be made to run internally in KCPB in V100 via a property and/or constructor parameter...
Might be owrth having a look at...
